### ISSUE TITLE
Single theater undefined when server render

### ISSUE THREAD

**Issue by Asing1001** [Asing1001/movieRater.React#48]
Example : 
https://www.mvrater.com/theater/%E5%96%9C%E6%BB%BF%E5%AE%A2%E4%BA%AC%E8%8F%AF%E5%BD%B1%E5%9F%8E

Log : 
```
09 Feb 2018 00:38:15.327150 <190>1 2018-02-08T16:38:14.944327+00:00 app web.1 - - TypeError: Cannot read property 'schedules' of undefined
    at TheaterDetail.render (/app/dist/app/components/theaterDetail.js:76:21)
    at walkTree (/app/node_modules/react-apollo/react-apollo.umd.js:709:32)
    at walkTree (/app/node_modules/react-apollo/react-apollo.umd.js:719:13)
    at getQueriesFromTree (/app/node_modules/react-apollo/react-apollo.umd.js:739:5)
    at getDataFromTree (/app/node_modules/react-apollo/react-apollo.umd.js:754:19)
    at /app/node_modules/react-apollo/react-apollo.umd.js:761:41
09 Feb 2018 00:38:15.347365 <158>1 2018-02-08T16:38:14.946009+00:00 heroku router - - at=info method=GET path="/theater/%E5%96%9C%E6%A8%82%E6%99%82%E4%BB%A3%E5%BD%B1%E5%9F%8E" host=www.mvrater.com request_id=0fbfcaef-3f54-4ec3-9cad-022014fcae5e fwd="123.194.129.213,162.158.224.156" dyno=web.1 connect=2ms service=18ms status=500 bytes=323 protocol=http
```

**Comment by Asing1001** [comment]
No error occur in client side, so suspect encoding/decoding issue

**Comment by Asing1001** [comment]
202b12c
